## master 数据源配置
master:
  datasource:
    url: jdbc:mysql://localhost:3306/xmairtravel_reserve?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

  ## slave 数据源配置
slave:
  datasource:
    url: jdbc:mysql://localhost:3306/xmairtravel_reserve?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

#热部署
spring:
  captchaType: math
  http:
    encoding:
      force: true
      charset: UTF-8
  devtools:
    restart:
      enabled: true

token:
  # 加密密钥
  secret: iwqjhda8232bjgh432[cicada-smile]
  # token有效时长
  expireTime: 3600
