## master 数据源配置
master:
  datasource:
    url: jdbc:mysql://39.103.196.2:3306/xmairtravel_reserve?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

  ## slave 数据源配置
slave:
  datasource:
    url: jdbc:mysql://39.103.196.2:3306/xmairtravel_reserve?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

#热部署
spring:
  redis:
    host: 39.103.196.2
  http:
    encoding:
      force: true
      charset: UTF-8
  devtools:
    restart:
      enabled: true

wx:
  appid: wx690beb152e635c0b
  appsecret: 4b5e8008b2474f2432055ebdc2460802
  openid: o9JP40K2b4iaF0ylB_rv-H1LF_sU
  token: 56_2foask0HSN-jcB7wyhfyqU0l5ZyantJ6DkuOMxAaDbH73luM0Fmw-IcINg_D-zLuyVwOmLFMu5dSpJhOFDnWKcDbSJFwye_ePiCGWsH6ZUja0aNZlpw7gG6TgF5-w6RyNvIRSAmnsFR4I2FuUQXcAAAPLS